[package]
name = "tokio-retry"
version = "0.1.1"
authors = ["Sam Rijs <srijs@airpost.net>"]
description = "Extensible, asynchronous retry behaviours for futures/tokio"
license = "MIT"
repository = "https://github.com/srijs/rust-tokio-retry"
documentation = "https://docs.rs/tokio-retry"
keywords = ["futures", "tokio", "retry", "backoff", "middleware"]

[dependencies]
futures = "0.1.11"
rand = "0.4.0"
tokio-core = "0.1.6"
tokio-service = "0.1.0"

[dev-dependencies]
quickcheck = "0.4.1"
